### ISSUE TITLE
Smarty or Template Error

### ISSUE THREAD

**Issue by DIOHz0r** [TickyBoo/TickyBoo#4]
I still don't know who is generating this error every time that I'm triying to print anything (invoice or ticket)....
I'm using PHP5.3, Apache 2.2 and Win7 

Fatal error: Uncaught exception 'SmartyCompilerException' with message 'Syntax Error in template "87642ad2685d190e79afdd102617c3d77a3f713b" on line 21 "{if $event_name|count_characters:true &lt; 20}" unknown modifier "count_characters"' in D:\webs\tecnoticket\includes\libs\smarty3\sysplugins\smarty_internal_templatecompilerbase.php:625 Stack trace: #0 D:\webs\tecnoticket\includes\libs\smarty3\sysplugins\smarty_internal_compile_private_modifier.php(73): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown modifie...', 21) #1 D:\webs\tecnoticket\includes\libs\smarty3\sysplugins\smarty_internal_templatecompilerbase.php(439): Smarty_Internal_Compile_Private_Modifier->compile(Array, Object(Smarty_Internal_SmartyTemplateCompiler), Array, NULL, NULL) #2 D:\webs\tecnoticket\includes\libs\smarty3\sysplugins\smarty_internal_templatecompilerbase.php(227): Smarty_Internal_TemplateCompilerBase->callTagCompiler('private_modifie...', Array, Array) #3 D:\webs\tecnoticket\includes\libs\smarty3\sysplugins\smarty_internal_ in D:\webs\tecnoticket\includes\libs\smarty3\sysplugins\smarty_internal_templatecompilerbase.php on line 625

**Comment by DIOHz0r** [comment]
I found the problem, at the ticket's template on line 21 you'll find the line {if $eventname|count_characters:true < 20}, if you remove the if condition and compile the template you won't have the error printting the tickets. The smarty property 'count_characters' exist so I sill don't know why this is throwing an error.
